#!/bin/sh /etc/rc.common
START=99

USE_PROCD=1

NAME=nut_client_service
PROG=/root/nut_client_service
OPT_CONFIG=/root/nut_client_service.yml

boot() {
    start
}

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" --config=$OPT_CONFIG
    procd_close_instance
}

stop() {
    service_stop $PROG
}

reload() {
    service_reload $PROG
}