logging:
  file: "./nut_client_service.log"
  level: "fatal"

http:
  host: "0.0.0.0"
  port: 6080
  bodyLimit: 1048576

clients:
  nut:
      host: "127.0.0.1"
      port: 3493
      username: "nut_client_service"
      password: "1234567890"

metrics:
  nut:
    interval: "1s"