logging:
  file: "./bin/nut_client_service.log"
  level: "debug"

http:
  host: "0.0.0.0"
  port: 6080
  bodyLimit: 1048576

clients:
  nut:
      host: "127.0.0.1"
      port: 3493
      username: ""
      passord: ""

metrics:
  nut:
    interval: "1s"