{
 "title": "UPS states",
 "description": "Process status and runtime metrics published by Go Prometheus client and UPS state",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "ups_name",
    "label": "UPS name",
    "query": {
     "query": "nut_client_service_ups_variables{job=\"nut_client_service\"}"
    }
   },
   {
    "name": "ups_service",
    "label": "UPS service",
    "query": {
     "query": "nut_client_service_ups_variables{job=\"nut_client_service\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UPS status",
   "type": "stat",
   "description": "Current UPS Status (0=Calibration, 1=SmartTrim, 2=SmartBoost, 3=Online, 4=OnBattery, 5=Overloaded, 6=LowBattery, 7=ReplaceBattery, 8=OnBypass, 9=Off, 10=Charging, 11=Discharging)",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"ups.status\",instance=\"$ups_service\"}",
     "legendFormat": "UPS status"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"ups.temperature\",instance=\"$ups_service\"}",
     "legendFormat": "UPS temperature (degrees C)"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"ups.load\",instance=\"$ups_service\"}",
     "legendFormat": "Load on UPS"
    },
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"battery.charge\",instance=\"$ups_service\"}",
     "legendFormat": "Battery charge"
    }
   ]
  },
  {
   "title": "Input",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"input.voltage\",instance=\"$ups_service\"}",
     "legendFormat": "Voltage (V)"
    },
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"input.frequency\",instance=\"$ups_service\"}",
     "legendFormat": "Line frequency (Hz)"
    }
   ]
  },
  {
   "title": "Input voltage (V)",
   "type": "graph",
   "description": "Input voltage (V)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"input.voltage\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  { "title": "UPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Battery charge (percent of full)",
   "type": "graph",
   "description": "Battery charge (percent of full)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"battery.charge\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Remaining battery for LB",
   "type": "gauge",
   "description": "Remaining battery level when UPS switches to LB (percent)",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"battery.charge.low\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Battery level for Warning",
   "type": "gauge",
   "description": "Battery level when UPS switches to Warning state (percent)",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"battery.charge.warning\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Interval to wait after shutdown",
   "type": "gauge",
   "description": "Interval to wait after shutdown with delay command (seconds)",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"ups.delay.shutdown\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Interval to wait before (re)starting",
   "type": "gauge",
   "description": "Interval to wait before (re)starting the load (seconds)",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"ups.delay.start\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Battery voltage (V)",
   "type": "graph",
   "description": "Battery voltage (V)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"battery.voltage\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Nominal battery voltage (V)",
   "type": "graph",
   "description": "Nominal battery voltage (V)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"battery.voltage.nominal\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Nominal input current (A)",
   "type": "graph",
   "description": "Nominal input current (A)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"input.current.nominal\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Input line frequency (Hz)",
   "type": "graph",
   "description": "Input line frequency (Hz)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"input.frequency\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Nominal input line frequency (Hz)",
   "type": "graph",
   "description": "Nominal input line frequency (Hz)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"input.frequency.nominal\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Input voltage (V)",
   "type": "graph",
   "description": "Input voltage (V)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"input.voltage\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Nominal input voltage (V)",
   "type": "graph",
   "description": "Nominal input voltage (V)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"input.voltage.nominal\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Output voltage (V)",
   "type": "graph",
   "description": "Output voltage (V)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"output.voltage\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "Load on UPS (percent of full)",
   "type": "graph",
   "description": "Load on UPS (percent of full)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"ups.load\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "UPS temperature (degrees C)",
   "type": "graph",
   "description": "UPS temperature (degrees C)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",variable=\"ups.temperature\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "All Vars",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nut_client_service_ups_variables{job=\"nut_client_service\",ups=\"$ups_name\",instance=\"$ups_service\"}",
     "legendFormat": "{{variable}}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Summary RPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nut_client_service_http_response_time_seconds_count{job=\"nut_client_service\",instance=\"$ups_service\"}[$__rate_interval]))",
       "legendFormat": "summary"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(nut_client_service_http_response_time_seconds_count{job=\"nut_client_service\",instance=\"$ups_service\"}[$__rate_interval])",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(nut_client_service_http_response_time_seconds_bucket{job=\"nut_client_service\",instance=\"$ups_service\"}[$__rate_interval]))",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "Summary RPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nut_client_service_http_response_time_seconds_count{job=\"nut_client_service\",instance=\"$ups_service\"}[$__rate_interval]))",
       "legendFormat": "summary"
      }
     ]
    }
   ]
  },
  {
   "title": "misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"nut_client_service\",instance=\"$ups_service\"}",
       "legendFormat": "{{hostname}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "pointer deferences",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=\"nut_client_service\",instance=\"$ups_service\"}[$__rate_interval])",
       "legendFormat": "Pointer dereferences"
      }
     ]
    }
   ]
  },
  {
   "title": "file descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=\"nut_client_service\",instance=\"$ups_service\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "deriv(process_open_fds{job=\"nut_client_service\",instance=\"$ups_service\"}[$interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "goroutine stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"nut_client_service\",instance=\"$ups_service\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "OS Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{job=\"nut_client_service\",instance=\"$ups_service\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "alloc bytes allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"nut_client_service\",instance=\"$ups_service\"}",
       "legendFormat": "{{hostname}} - bytes allocated"
      }
     ]
    },
    {
     "title": "alloc bytes allocated - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{job=\"nut_client_service\",instance=\"$ups_service\"}[$interval])",
       "legendFormat": "{{hostname}} - bytes allocated"
      }
     ]
    },
    {
     "title": "stack in use - bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"nut_client_service\",instance=\"$ups_service\"}",
       "legendFormat": "{{hostname}} - stack inuse"
      }
     ]
    },
    {
     "title": "stack in use - bytes - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{job=\"nut_client_service\",instance=\"$ups_service\"}[$interval])",
       "legendFormat": "{{hostname}} - stack inuse"
      }
     ]
    },
    {
     "title": "heap in use - bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"nut_client_service\",instance=\"$ups_service\"}",
       "legendFormat": "{{hostname}} - heap inuse"
      }
     ]
    },
    {
     "title": "heap in use - bytes - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{job=\"nut_client_service\",instance=\"$ups_service\"}[$interval])",
       "legendFormat": "{{hostname}} - heap inuse"
      }
     ]
    },
    {
     "title": "total alloc bytes allocation rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"nut_client_service\",instance=\"$ups_service\"}[30s])",
       "legendFormat": "{{hostname}} - alloc rate"
      }
     ]
    }
   ]
  },
  {
   "title": "process memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "process resident memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"nut_client_service\",instance=\"$ups_service\"}",
       "legendFormat": "{{hostname}} - resident"
      }
     ]
    },
    {
     "title": "process resident memory derivative",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{job=\"nut_client_service\",instance=\"$ups_service\"}[$interval])",
       "legendFormat": "{{hostname}} - resident"
      }
     ]
    },
    {
     "title": "process virtual memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{job=\"nut_client_service\",instance=\"$ups_service\"}",
       "legendFormat": "{{hostname}} - virtual"
      }
     ]
    },
    {
     "title": "process virtual memory derivative",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(process_virtual_memory_bytes{job=\"nut_client_service\",instance=\"$ups_service\"}[$interval])",
       "legendFormat": "{{hostname}} - virtual"
      }
     ]
    }
   ]
  }
 ]
}